server:
  port: 1012
  contextPath: /ms-web

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/WEB-INF/views/

