#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
##    url: jdbc:mysql://localhost/recon_db?useUnicode=true&characterEncoding=UTF8
##    username: crp
##    password: mysqlcrp_123
#  #数据库连接池配置
#    max-active: 50
#    max-idle: 20
#    min-idle: 10
#    initial-size: 2
#    test-on-borrow: true
#    test-on-return: true
#    test-while-idle: true
#    validation-query: select 1
#    #每10分钟收集空闲连接，单位毫秒
#    time-between-eviction-runs-millis: 600000
#    num-tests-per-eviction-run: 50
#    #连接的最大空闲时间，单位毫秒，60分钟
#    min-evictable-idle-time-millis: 3600000
#    max-wait: 60000


logging:
  config: classpath:logback.xml
  level.*: INFO

